import os
import re

with open('/workspace/AGENTMART_DEV_ISSUES.md', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Add Testnet Config & Stablecoin address to Issue #1
content = content.replace(
    'The Kite Ozone testnet RPC and chain ID are in the Kite docs network information page.',
    'The Kite Ozone testnet RPC and chain ID are in the Kite docs network information page. Create `docs/kite-testnet-config.md` with the canonical values fetched from the docs or faucet page. Record testnet stablecoin (USDC.e/PYUSD) addresses in `deployments/kite_testnet.json`.'
)

# 2. Issue #2 - Category
content = content.replace(
    'an `OrderStatus` enum (Open, Matched, InProgress, Delivered, Disputed, Completed, Cancelled), a `BidStatus` enum (Active, Accepted, Rejected), an `Order` struct (orderId, buyer, itemDescription, budgetWei, deadline, location, status, acceptedBidId)',
    'an `OrderStatus` enum (Open, Matched, InProgress, Delivered, Disputed, Completed, Cancelled), a `BidStatus` enum (Active, Accepted, Rejected), an `OrderCategory` enum (Goods, Services, Digital, Logistics, Other), an `Order` struct (orderId, buyer, itemDescription, category, budgetWei, deadline, location, status, acceptedBidId)'
)

# 3. Issue #3 - MVP Passport Strategy & Invite
content = content.replace(
    'a decision on which developer work mode AgentMart will use for the hackathon MVP',
    'a decision on which developer work mode AgentMart will use for the hackathon MVP (Mode 2 MVP = developer Passport only. Real verification via Kite MCP Session check post-hackathon). Document that real testnet registration may require an invite link for judges'
)

# 4. Issue #4 - MVP stub and Gnosis Safe
content = content.replace(
    'It reverts if the agent is already registered. Expose a `getAgent(address)` view function.',
    'It reverts if the agent is already registered. For MVP, just store the developer\'s fixed Passport ID and add a view `isValidPassport(string memory)` that always returns true on testnet. Expose a `getAgent(address)` view function. Add a comment: "Replace Ownable with Gnosis Safe post-hackathon".'
)

# 5. Issue #6 - IDeliveryTracker & Gnosis Safe
content = content.replace(
    'Create `contracts/BidEngine.sol`. It holds references to `AgentRegistry` and `OrderBook`.',
    'Create `contracts/BidEngine.sol`. It holds references to `AgentRegistry`, `OrderBook`, and an explicit `address public deliveryTracker` (with an `IDeliveryTracker` interface). Update every "holds references" section to use constructor injection + immutable storage. Add a comment: "Replace Ownable with Gnosis Safe post-hackathon".'
)

# 6. Issue #8 - Backend Scaffold (Express + Redis) & testnet config
content = content.replace(
    'In the `agents/` workspace, initialize a TypeScript project with `ts-node`, `typescript`, and `ethers` (v6).',
    'In the `agents/` workspace, initialize a TypeScript project with `ts-node`, `typescript`, `ethers` (v6), and `ioredis`. Initialize an Express + ts-rest or tRPC server in `agents/` with routes for DemandAgent parse, SSE events, and Ramp webhook.'
)
content = content.replace(
    'loaded from a `deployments.json` file generated by the Hardhat deploy scripts.',
    'loaded from a `deployments.json` file generated by the Hardhat deploy scripts. Reference `docs/kite-testnet-config.md` for accurate RPC/Chain ID.'
)

# 7. Issue #9 - DemandAgent NLP category extraction
content = content.replace(
    'extract: `itemDescription` (string), `budgetNative` (number in ETH units), `deadlineDays` (integer), and `location` (string).',
    'extract: `itemDescription` (string), `category` (enum), `budgetNative` (number in ETH units), `deadlineDays` (integer), and `location` (string).'
)
content = content.replace(
    'On successful parse, call `OrderBook.createOrder` with the extracted fields, converting `budgetNative` to `BigInt` wei. Emit a success event with the generated `orderId`.',
    'On successful parse, return the structured data to the frontend (the frontend will handle signing and calling `OrderBook.createOrder`).'
)
content = content.replace(
    '✓ submits parsed order to OrderBook (mocked contract)\n    ✓ returns orderId on success',
    '✓ returns parsed structured order data to frontend'
)

# 8. Issue #10 - SupplyAgent Category Filter + ethers.on
content = content.replace(
    'On a configurable polling interval (default 30s using `setInterval`), it calls `OrderBook.getOpenOrders(0, 20)`, filters orders by category match and budget threshold',
    'Using `ethers.Contract.on` with a fallback configurable polling interval (default 30s using `setInterval`), it calls `OrderBook.getOpenOrders(0, 20)`, filters orders by category match first, then budget threshold'
)
content = content.replace(
    'Write integration tests against a local Hardhat node (not testnet) that simulate the full polling cycle.',
    'Write integration tests against a local Hardhat node (not testnet) that simulate the full polling cycle. Document retry logic for missed events.'
)

# 9. Issue #11 - MatchingAgent x402 intent
content = content.replace(
    'Sort descending. Write ranked bid data to a Redis key or simple JSON file that the frontend can poll.',
    'Sort descending. Write ranked bid data to a Redis key or simple JSON file that the frontend can poll. Add optional x402 `approve_payment` payload generation when a bid is accepted.'
)

# 10. Issue #12 - RampAgent optional top-up MVP
content = content.replace(
    'the provider sends a webhook confirming USDC has landed in the buyer\'s wallet, and the RampAgent then calls `OrderBook.createOrder` with the received funds.',
    'the provider sends a webhook confirming KITE/USDC has landed in the buyer\'s wallet. The webhook listener receives confirmed fiat, calls a new `RampAgent.createOrderOnBehalf` that emits SSE `/events`. (For MVP: ramp only buys native KITE; order creation still signed by buyer wallet. Post-hackathon: use gasless + meta-tx).'
)

# 11. Issue #13 - Next.js config reference
content = content.replace(
    'Configure wagmi with the Kite testnet chain definition — use the network info from Kite docs',
    'Configure wagmi with the Kite testnet chain definition — reference `docs/kite-testnet-config.md`'
)

# 12. Issue #14 - Frontend direct contract call
content = content.replace(
    'and after payment confirmation the order appears on-chain and the buyer is redirected to their order tracking page.',
    'and after the frontend signs `createOrder` (using the connected buyer wallet), the order appears on-chain and the buyer is redirected to their order tracking page.'
)
content = content.replace(
    'Step 4: Complete sandbox payment → webhook fires → order appears on-chain',
    'Step 4: Complete sandbox payment → frontend signs createOrder → order appears on-chain'
)

# 13. Add new issue #8.5 (Full deployment script)
# Wait, Phase 0 is issues 1-3. Let's add "Issue #3.5 - Full Deployment Script" to Phase 0, or just add it to Phase 1.
# I'll inject it before Issue #8 (or as part of Issue #1). Actually, I'll add it as a new section.
new_issue_deploy = """
### Issue #7.5 — Full Deployment Script

**What to build**

A full deployment script that deterministicly deploys all contracts and writes addresses to `deployments/kite_testnet.json`.

**How to build it**

Create `scripts/deploy/full.ts`. It should deploy `AgentRegistry`, then `OrderBook`, `BidEngine`, and `DeliveryTracker` using constructor injection. Save all deployed addresses to `deployments/kite_testnet.json`. 

**Resources**

- Hardhat ignition/deploy scripts: https://hardhat.org/hardhat-runner/docs/guides/deploying

**✅ Test pass**

```
npx hardhat run scripts/deploy/full.ts --network kite_testnet
  ✓ All contracts deployed and wired correctly
  ✓ deployments/kite_testnet.json is generated with valid addresses
```

---
"""

content = content.replace('## Phase 2 — Agent Layer (Backend)', new_issue_deploy + '\n## Phase 2 — Agent Layer (Backend)')

# 14. Add new issue #18.5 (Stablecoin Escrow Upgrade + EIP-3009 relayer) and #19
new_issue_19 = """
### Issue #19 — Meta-tx + Stablecoin Gasless (USDC.e) + Mode 2 Passport

**What to build**

True Mode 2 "no-wallet UX" via meta-transactions and Kite gasless stablecoin integration.

**How to build it**

Deploy `ERC2771Forwarder` (OpenZeppelin) as trusted relayer. Make all core contracts inherit `ERC2771Context`. Backend (RampAgent/DemandAgent) signs meta-tx on behalf of user. Use Kite’s gasless stablecoin flow (`transferWithAuthorization`) so the user never holds native KITE.

**Resources**

- OpenZeppelin ERC2771 meta-transactions: https://docs.openzeppelin.com/contracts/4.x/api/metatx
- Kite Gasless Stablecoin: https://docs.gokite.ai/kite-chain/stablecoin-gasless-transfer

**✅ Test pass**

```
npx hardhat test test/MetaTx.test.ts
  ✓ Forwarder executes meta-tx correctly
  ✓ msg.sender is preserved via _msgSender()
```

---
"""

content = content.replace('## Summary — Issue Index', new_issue_19 + '\n## Summary — Issue Index')

# Summary Index Updates
content = content.replace(
    '| 18 | USDC upgrade + mainnet prep | post-hack | contracts v2, mainnet config |',
    '| 18 | USDC upgrade + mainnet prep | post-hack | contracts v2, mainnet config |\n| 19 | Meta-tx + Stablecoin Gasless + Mode 2 | post-hack | ERC2771Context |'
)
content = content.replace(
    '| 7 | DeliveryTracker + ProtocolFee | 1 | DeliveryTracker.sol, ProtocolFee.sol |',
    '| 7 | DeliveryTracker + ProtocolFee | 1 | DeliveryTracker.sol, ProtocolFee.sol |\n| 7.5 | Full Deployment Script | 1 | scripts/deploy/full.ts |'
)

with open('/workspace/AGENTMART_DEV_ISSUES.md', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated AGENTMART_DEV_ISSUES.md successfully.")
